version: 2
updates:
  # Maintain dependencies for Github Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"
    groups:
      github-actions:
        patterns:
          - "*"
    cooldown:
      default-days: 1
