#!/bin/sh
set -e

# Default torrc path
TORRC="/etc/tor/torrc"

# Clear existing torrc or create a new one
echo "# Generated by entrypoint.sh" > $TORRC

# Function to convert to CamelCase
to_camel_case() {
    echo "$1" | awk 'BEGIN{FS="_";OFS=""} {for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr(tolower($i),2)} 1'
}

# Process environment variables
env | while IFS='=' read -r key value
do
    if [[ $key == TOR_* ]]
    then
        # Remove TOR_ prefix and convert to CamelCase
        torrc_key=$(to_camel_case "${key#TOR_}")
        # Append to torrc
        echo "$torrc_key $value" >> $TORRC
    fi
done

# Print the generated torrc for debugging
echo "Generated torrc:"
cat $TORRC

# Start Tor with the generated config
exec tor -f $TORRC
