#!/bin/sh
set -e

# Default torrc path
TORRC="/etc/tor/torrc"

# Clear existing torrc or create a new one
echo "# Generated by entrypoint.sh" > $TORRC

# Function to convert to CamelCase
to_camel_case() {
    echo "$1" | awk 'BEGIN{FS="_";OFS=""} {for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr(tolower($i),2)} 1'
}

# Process environment variables for general Tor configuration
env | sort | while IFS='=' read -r key value
do
    case "$key" in
        TOR_*)
            case "$key" in
                TOR_HIDDEN_SERVICE_VERSION) ;;  # Skip, we'll handle this separately
                TOR_HIDDEN_SERVICE_DIR) ;;      # Skip, we'll handle this separately
                TOR_HIDDEN_SERVICE_PORT) ;;     # Skip, we'll handle this separately
                *_TOR_HIDDEN_SERVICE_*) ;;      # Skip, we'll handle this separately
                *)
                    # Remove TOR_ prefix and convert to CamelCase
                    torrc_key=$(to_camel_case "${key#TOR_}")
                    # Append to torrc
                    echo "$torrc_key $value" >> $TORRC
                    ;;
            esac
            ;;
    esac
done

# Get the HiddenServiceVersion if set
hidden_service_version=${TOR_HIDDEN_SERVICE_VERSION:-""}

# Function to write hidden service configuration
write_hidden_service_config() {
    local dir="$1"
    local prefix="$2"

    echo "HiddenServiceDir $dir" >> $TORRC
    if [ -n "$hidden_service_version" ]; then
        echo "HiddenServiceVersion $hidden_service_version" >> $TORRC
    fi

    # First try exact port match
    if [ "$prefix" = "TOR" ]; then
        # Handle unprefixed TOR_HIDDEN_SERVICE_PORT
        port_value="$TOR_HIDDEN_SERVICE_PORT"
    else
        port_value=$(env | grep "^${prefix}_TOR_HIDDEN_SERVICE_PORT=" | cut -d'=' -f2-)
    fi

    if [ -n "$port_value" ]; then
        echo "HiddenServicePort $port_value" >> $TORRC
    else
        # Then try multi-port matches
        env | sort | while IFS='=' read -r port_key port_value
        do
            case "$port_key" in
                ${prefix}_*_TOR_HIDDEN_SERVICE_PORT)
                    echo "HiddenServicePort $port_value" >> $TORRC
                    ;;
            esac
        done
    fi

    echo "" >> $TORRC
}

# Handle default TOR_HIDDEN_SERVICE_* configuration
if [ -n "$TOR_HIDDEN_SERVICE_DIR" ]; then
    write_hidden_service_config "$TOR_HIDDEN_SERVICE_DIR" "TOR"
fi

# Process all other hidden services
processed_dirs=""

env | sort | while IFS='=' read -r key value
do
    case "$key" in
        *_TOR_HIDDEN_SERVICE_DIR)
            prefix=${key%_TOR_HIDDEN_SERVICE_DIR}
            dir_value="$value"

            # Skip if we've already processed this directory
            if ! echo "$processed_dirs" | grep -q "^${dir_value}$"; then
                write_hidden_service_config "$dir_value" "$prefix"
                processed_dirs="${processed_dirs}${dir_value}\n"
            fi
            ;;
    esac
done

# Print the generated torrc for debugging
echo "Generated torrc:"
cat $TORRC

# Function to get hostname from hidden service directory
get_hostname() {
    if [ -f "$1/hostname" ]; then
        cat "$1/hostname"
    else
        echo "N/A (hostname file not found)"
    fi
}

# Function to print service and hostname with consistent indentation
print_service_hostname() {
    printf "%-15s %s\n" "$1:" "$2"
}

# Start Tor in the background
tor -f $TORRC &
tor_pid=$!

sleep 1

# Print Hidden Service Hostnames
echo ""
echo "======== Hidden Service Hostnames ========"

# Print default hidden service if exists
if [ -n "$TOR_HIDDEN_SERVICE_DIR" ]; then
    print_service_hostname "default" "$(get_hostname "$TOR_HIDDEN_SERVICE_DIR")"
fi

# Print prefixed hidden services
env | sort | while IFS='=' read -r key value
do
    case "$key" in
        *_TOR_HIDDEN_SERVICE_DIR)
            if [ "$key" != "TOR_HIDDEN_SERVICE_DIR" ]; then  # Skip the default one as we already printed it
                service_name=$(echo "${key%_TOR_HIDDEN_SERVICE_DIR}" | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')
                print_service_hostname "$service_name" "$(get_hostname "$value")"
            fi
            ;;
    esac
done

echo "=========================================="

# Wait for Tor to exit
wait $tor_pid
