name: Docker Build

on:
  push:
    branches:
      - master
    tags:
      - "*"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Extract Tag
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            FULL_VERSION=${GITHUB_REF#refs/tags/}
            SHORT_VERSION=$(echo $FULL_VERSION | cut -d'-' -f1)
            echo "FULL_TAG=$FULL_VERSION" >> $GITHUB_OUTPUT
            echo "SHORT_TAG=$SHORT_VERSION" >> $GITHUB_OUTPUT
            echo "IS_TAG=true" >> $GITHUB_OUTPUT
          else
            echo "IS_TAG=false" >> $GITHUB_OUTPUT
          fi
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/tor
          tags: |
            type=raw,value=latest,enabled=${{ github.event_name != 'schedule' && (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) || steps.version.outputs.IS_TAG == 'true') }}
            type=raw,value=${{ steps.version.outputs.FULL_TAG }},enabled=${{ steps.version.outputs.IS_TAG == 'true' }}
            type=raw,value=${{ steps.version.outputs.SHORT_TAG }},enabled=${{ steps.version.outputs.IS_TAG == 'true' }}
            type=schedule,pattern={{date 'YYYYMMDD'}}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha,scope=build-tor
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/tor:latest
          cache-to: type=gha,mode=max,scope=build-tor
          platforms: linux/amd64,linux/arm64
          build-args: |
            TOR_VERSION=${{ steps.version.outputs.IS_TAG == 'true' && steps.version.outputs.FULL_TAG || 'latest' }}
