name: Docker Build

on:
  push:
    branches:
      - master
    tags:
      - "*"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: docker/setup-buildx-action@v3
        with:
          install: true
          version: latest
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Extract Tag
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            FULL_VERSION=${GITHUB_REF#refs/tags/}
            SHORT_VERSION=$(echo $FULL_VERSION | cut -d'-' -f1)
            echo "FULL_TAG=$FULL_VERSION" >> $GITHUB_OUTPUT
            echo "SHORT_TAG=$SHORT_VERSION" >> $GITHUB_OUTPUT
          fi
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/tor
          tags: |
            type=raw,value=latest,enable=${{ github.ref_type == 'tag' }}
            type=ref,event=branch,enable=${{ github.event_name != 'schedule' }}
            type=ref,event=branch,suffix=-{{sha}},enable=${{ github.event_name != 'schedule' }}
            type=raw,value=${{ steps.version.outputs.FULL_TAG }},enable=${{ github.ref_type == 'tag' }}
            type=raw,value=${{ steps.version.outputs.SHORT_TAG }},enable=${{ github.ref_type == 'tag' }}
            type=schedule,pattern={{date 'YYYYMMDD'}}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            TOR_VERSION=${{ github.ref_type == 'tag' && steps.version.outputs.FULL_TAG || 'latest' }}
