name: Docker Build

on:
  push:
    branches:
      - master
    tags:
      - "*"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/tor
          tags: |
            type=raw,value=latest,enabled={{is_default_branch}}
            type=pep440,pattern={{version}}
            type=schedule,pattern={{date 'YYYYMMDD'}}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha,scope=build-tor
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/tor:latest
          cache-to: type=gha,mode=max,scope=build-tor
          platforms: linux/amd64,linux/arm64
          build-args: |
            TOR_VERSION=${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'latest' }}
